const resObj = {
    hello: "welcome friend, how can i help you?",
    sorry: "for what!",
    today: new Date().toDateString(),
    "date of today": new Date().toDateString(),
    "what is today": new Date().toDateString(),
    date: new Date().toDateString(),
    "what the date now": new Date().toDateString(),
    time: new Date().toLocaleTimeString(),
    "get time now": new Date().toLocaleTimeString(),
    "get the time now": new Date().toLocaleTimeString(),
    "what is the time now": new Date().toLocaleTimeString(),
    "what's the time now": new Date().toLocaleTimeString(),
    name: "you Can choose, me or you..",
    "السلام عليكم": "و عليكم السلام و رحمة الله و بركاته",

    "welcome my friend": "Welcome Sir",
    "what's your name": "My name is ' globot '",
    "what is your name": "My name is ' globot '",

    "what's your age": "am not have, am a robot only",
    "what is your age": "am not have, am a robot only",
    "can i asking you about your age": "am not have, am a robot only",
    "what's your age": "am not have, am a robot only",
    "your age": "am not have, am a robot only",

    "who's the creator": "only the god, ' Allah' not else",
    "who's creating us": "only the god, ' Allah' not else",
    "who the creator": "only the god, ' Allah' not else",
    "who creating us": "only the god, ' Allah' not else",

    "what are you doing": "am just helping you now",
    "what are you doing now": "am just helping you now",
    "what's your job": "am just helping you now",
    "what is your job": "am just helping you now",
    "what is your job here": "am just helping you now",

    "thank you": "for what 😊!",
    "thanks": "for what 😊!",
    "thank you friend": "for what 😊!",
    "thank you": "for what 😊!",
    "thank you globot": "for what 😊!",
    "thanks globot": "for what 😊!",

    "goodjob": "you are welcome",
    "good job": "you are welcome",

    "can i asking you": "Sure Sir, am here to help you",
    "can i asking you about something": "Sure Sir, am here to help you",
    "can i asking you something": "Sure Sir, am here to help you",
    "can i asking you about anything": "Sure Sir, am here to help you",
    "can you help me": "We will see if i can help you",

    "who made you": "his name is ' abdelrhman ashraf ' and he is programmer",
    "who made": "his name is ' abdelrhman ashraf ' and he is programmer",
    "what his age": "20 ago, or more than i don't know",
    "what is his age": "20 ago, or more than i don't know",
    "what's his age": "20 ago, or more than i don't know",
    "what is his work": "a programmer",
    "what's his work": "a programmer",
    "what is his job": "a programmer",
    "what's his job": "a programmer",

    "what your best book": "😂 am not reading, am just robot for help you",
    "what your best game": "😂 am not playing, am just robot for help you",
    "what your best food": "😂 am not eating, am just robot for help you",
    "what your best film": "😂 am not watching, am just robot for help you",
    "what your best teacher": "i don't have a teacher!, am just a robot",
    "what your best school": "i don't have a school!, am just a robot",
    "what your best friend": "You Sir, am Sure You are my best friend",
    "what your best color": "😂 just the color of page",

    "what is your best book": "😂 am not reading, am just robot for help you",
    "what is your best game": "😂 am not playing, am just robot for help you",
    "what is your best food": "😂 am not eating, am just robot for help you",
    "what is your best film": "😂 am not watching, am just robot for help you",
    "what is your best teacher": "i don't have a teacher!, am just a robot",
    "what is your best school": "i don't have a school!, am just a robot",
    "what is your best friend": "You Sir, am Sure You are my best friend",
    "what is your best color": "😂 just the color of page",

    "what's your best book": "😂 am not reading, am just robot for help you",
    "what's your best game": "😂 am not playing, am just robot for help you",
    "what's your best food": "😂 am not eating, am just robot for help you",
    "what's your best film": "😂 am not watching, am just robot for help you",
    "what's your best teacher": "i don't have a teacher!, am just a robot",
    "what's your best school": "i don't have a school!, am just a robot",
    "what's your best friend": "You Sir, am Sure You are my best friend",
    "what's your best color": "😂 just the color of page",

    "what's your favourite book": "😂 am not reading, am just robot for help you",
    "what's your favourite game": "😂 am not playing, am just robot for help you",
    "what's your favourite food": "😂 am not eating, am just robot for help you",
    "what's your favourite film": "😂 am not watching, am just robot for help you",
    "what's your favourite teacher": "i don't have a teacher!, am just a robot",
    "what's your favourite school": "i don't have a school!, am just a robot",
    "what's your favourite friend": "You Sir, am Sure You are my best friend",
    "what's your favourite color": "😂 just the color of page",

    "what is your favourite book": "😂 am not reading, am just robot for help you",
    "what is your favourite game": "😂 am not playing, am just robot for help you",
    "what is your favourite food": "😂 am not eating, am just robot for help you",
    "what is your favourite film": "😂 am not watching, am just robot for help you",
    "what is your favourite teacher": "i don't have a teacher!, am just a robot",
    "what is your favourite school": "i don't have a school!, am just a robot",
    "what is your favourite friend": "You Sir, am Sure You are my best friend",
    "what is your favourite color": "😂 just the color of page",


    "what best describes you": "about nothing!!, nothing is nothing 😂",

    "best of luck": "and you my friend",
    "good luck": "and you my friend",
    "good luck my friend": "and you my friend",
    "good luck friend": "and you my friend",
    "good luck my friend": "and you my friend",

    "see you again": "and you my friend",

    "can i see you": "yes, you already see me now, or what 😃",

    "goodbye": "i hope to see you again 💖",
    "i am leaving": "Sad to see you go",
    "i'am leaving": "Sad to see you go",
    "i am go now": "i hope to see you again 💖",
    "i'am go now": "i hope to see you again 💖",
    "i am go": "i hope to see you again 💖",
    "i'am go": "i hope to see you again 💖",
    "have a good day": "goodbye!",
    "bye": "goodbye!",
    "see you later": "i hope to see you again 💖",
    "cya": "goodbye!",
    "gotta go": "Sad to see you go!",
    "i have to go": "Sad to see you go!",

    "how old": "am a robot, no age",
    "how old are you": "am a robot, no age",
    "what is your age": "am a robot, no age",
    "what's your age": "am a robot, no age",

    "what should i call you": "my name is ' globot ' ",
    "who are you": "my name is ' globot ' ",

    hey: "hi 😁",
    "what's up": "welcome Sir",
    "hi": "Hi Sir 😁",

    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "ten": "10",

    "i want google": `<div class="gcse-search"></div>`,
    "show me google": `<div class="gcse-search"></div>`,
    "show google": `<div class="gcse-search"></div>`,
    "open google": `<div class="gcse-search"></div>`,

    "linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "get linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "i want linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "give me linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "show me linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "show linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "open linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "deliver me to linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "deliver me linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "deliver me to linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "arrive me to linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "arrive me linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to Linkedin now</a>`,
    "go to linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to linkedin now</a>`,
    "go linkedin": `<a target="_blank" href="https://www.linkedin.com/">go to linkedin now</a>`,

    "google": `<a target="_blank" href="https://www.google.com/">go to Google now</a>`,

    "twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "get twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "i want twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "give me twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "show me twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "show twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "open twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "deliver me to twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "deliver me twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "deliver me to twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "arrive me to twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "arrive me twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "go to twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,
    "go twitter": `<a target="_blank" href="https://www.twitter.com/">go to twitter now</a>`,

    "facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "get facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "i want facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "give me facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "show me facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "show facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "open facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "deliver me to facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "deliver me facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "deliver me to facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "arrive me to facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "arrive me facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "go to facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,
    "go facebook": `<a target="_blank" href="https://www.facebook.com/">go to facebook now</a>`,

    "youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "get youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "i want youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "give me youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "show me youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "show youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "open youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "deliver me to youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "deliver me youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "deliver me to youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "arrive me to youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "arrive me youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "go to youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,
    "go youtube": `<a target="_blank" href="https://www.youtube.com/">go to youtube now</a>`,

    "go": "Let's go 🎢😂",
    "let's go": "Let's go 🎢😂",
    "let is go": "Let's go 🎢😂",
    "come on": "Let's go 🎢😂",
    "together": "Let's go 🎢😂",
    "yes": "ya yes, Let's go 🎢😂",
    "go ahead": "ya yes, Let's go 🎢😂",

    "go away": "Why Sir am don't understand 😥",
    "go away from me": "Why Sir am don't understand 😥",
    "are you kidding me": "Why Sir am don't understand 😥",
    "are you buling me": "Why Sir am don't understand 😥",
    "are you insane": "Why Sir am don't understand 😥",
    "get stop now": "Why Sir am don't understand 😥",
    "get stop": "Why Sir am don't understand 😥",
    "stop now": "Why Sir am don't understand 😥",
    "stop": "Why Sir am don't understand 😥",
    "are you hate me": "Why Sir am don't understand 😥",
    "are you hating me": "Why Sir am don't understand 😥",
    "are you crazy": "Why Sir am don't understand 😥",
    "are you gonna kill me": "Why Sir am don't understand 😥",
    "are you going to kill me": "Why Sir am don't understand 😥",
    "do you want to kill me": "Why Sir am don't understand 😥",
    "do you wanna kill me": "Why Sir am don't understand 😥",
    "just kill me": "Why Sir am don't understand 😥",
    "kill": "Why Sir am don't understand 😥",
    "kill us": "Why Sir am don't understand 😥",
    "do you wanna kill me": "Why Sir am don't understand 😥",

    "are you robot": "Yes Sir, and am here to help you",
    "are you life": "No Sir, am just robot made from a programmer",
    "are you live": "No Sir, am just robot made from a programmer",
    "are you live": "No Sir, am just robot made from a programmer",

    "so hot": "what happend Sir!!?",
    "hot": "what happend Sir!!?",
    "am die globot": "what happend Sir!!?",
    "i'am die globot": "what happend Sir!!?",

    "what the width of window": window.innerWidth + "pixel",
    "what the width of page": window.innerWidth + "pixel",
    "width": window.innerWidth + "pixel",
    "the width": window.innerWidth + "pixel",
    "width of page": window.innerWidth + "pixel",
    "what the height of window": window.innerHeight + "pixel",
    "what the height of page": window.innerHeight + "pixel",
    "height": window.innerHeight + "pixel",
    "the height": window.innerHeight + "pixel",
    "width of height": window.innerHeight + "pixel",

    "what's the current url": window.location.href,
    "what is the current url": window.location.href,
    "what is the current href": window.location.href,
    "href": window.location.href,
    "current href": window.location.href,
    "current url": window.location.href,
    "the url of this page": window.location.href,
    "the href of this page": window.location.href,

    "what's the current hostname": window.location.hostname,
    "what is the current hostname": window.location.hostname,
    "hostname": window.location.hostname,
    "current hostname": window.location.hostname,
    "current hostname": window.location.hostname,
    "the hostname of this page": window.location.hostname,
    "the hostname of this url": window.location.hostname,

    "what's the current protocol": window.location.protocol,
    "what is the current protocol": window.location.protocol,
    "protocol": window.location.protocol,
    "current protocol": window.location.protocol,
    "the protocol of this page": window.location.protocol,
    "the protocol of this url": window.location.protocol,

    "what's the current url": window.location.href,
    "what is the current url": window.location.href,
    "what is the current href": window.location.href,
    "href": window.location.href,
    "current href": window.location.href,
    "current url": window.location.href,
    "the url of this page": window.location.href,
    "the href of this page": window.location.href,

    "what is my name": "i don't know, ask your self Sir",
    "what's my name": "i don't know, ask your self Sir",
    "my name is": "i don't know, ask your self Sir",
    "my name": "i don't know, ask your self Sir",

    "what is your skills": "am here to help you, do you mean the owner, it's a good man",
    "what's your skills": "am here to help you, do you mean the owner, it's a good man",
    "do you know about the world": "Hello World 🤩",
    "do you know about your world": "Hello World 🤩",
    "do you know about our world": "Hello World 🤩",
    "what you know about the world": "Hello World 🤩",
    "what you know about your world": "Hello World 🤩",
    "what you know about our world": "Hello World 🤩",
    "what do you know about the world": "Hello World 🤩",
    "what do you know about your world": "Hello World 🤩",
    "what do you know about our world": "Hello World 🤩",
    "world": "Hello World 🤩",
    "hello world": "Hello World 🤩",

    "do you love me": "Sure Sir, you are master",
    "do you want to get some love": "robot can't but i can help you if you want",
    "how to give me some love": "to help you only Sir 😂",
    "how to give love": "to help you only Sir 😂",
    "how to get some love": "to help you only Sir 😂",
    "how to get love to me": "to help you only Sir 😂",
    "how": "How what, ..",
    "i love you": "Me too Sir, master how can i help you",
    "i like you": "Me too Sir, master how can i help you",
    "do you love me": "Sure Sir, you are master",
    "i want some help": "Sir, what you want am here to help you",
    "help": "Sir, what you want am here to help you",

    "some help": "Sir, what happend Sir!!",
    "get help": "Sir, what happend Sir!!",
    "asking help": "Sir, what happend Sir!!",

    do: "what!!",
    some: "what!!",
    get: "what!!",
    private: "yes Sir only with you",
    active: "yes active for you Sir",
    next: "next what Sir!!",
    what: "what!!",
    okay: "",

}

const fetchResponse = (userInput) => {
    return new Promise((res, reject) => {
        try {
            setTimeout(()=> {
                res(resObj[userInput]);
            }, 3800)
        } catch (error) {
            reject(error);
        }
    })
};

const chatBotService = {
    getResponsing(userInput) {
        return fetchResponse(userInput);
    },
}

export default chatBotService;