const resObj = {
    hello: "welcome friend, how can i help you?",
    sorry: "for what!",
    today: new Date().toDateString(),
    "date of today": new Date().toDateString(),
    "what is today": new Date().toDateString(),
    date: new Date().toDateString(),
    "what the date now": new Date().toDateString(),
    time: new Date().toLocaleTimeString(),
    "get time now": new Date().toLocaleTimeString(),
    "get the time now": new Date().toLocaleTimeString(),
    "what is the time now": new Date().toLocaleTimeString(),
    "what's the time now": new Date().toLocaleTimeString(),
    name: "you Can choose, me or you..",
    "السلام عليكم": "و عليكم السلام و رحمة الله و بركاته",

    "welcome my friend": "Welcome Sir",
    "what's your name": "My name is ' globot '",
    "what is your name": "My name is ' globot '",

    "what's your age": "am not have, am a robot only",
    "what is your age": "am not have, am a robot only",
    "can i asking you about your age": "am not have, am a robot only",
    "what's your age": "am not have, am a robot only",
    "your age": "am not have, am a robot only",

    "who's the creator": "only the god, ' Allah' not else",
    "who's creating us": "only the god, ' Allah' not else",
    "who the creator": "only the god, ' Allah' not else",
    "who creating us": "only the god, ' Allah' not else",

    "what are you doing": "am just helping you now",
    "what are you doing now": "am just helping you now",
    "what's your job": "am just helping you now",
    "what is your job": "am just helping you now",
    "what is your job here": "am just helping you now",

    "thank you": "for what 😊!",
    "thanks": "for what 😊!",
    "thank you friend": "for what 😊!",
    "thank you": "for what 😊!",
    "thank you globot": "for what 😊!",
    "thanks globot": "for what 😊!",

    "goodjob": "you are welcome",
    "good job": "you are welcome",

    "can i asking you": "Sure Sir, am here to help you",
    "can i asking you about something": "Sure Sir, am here to help you",
    "can i asking you something": "Sure Sir, am here to help you",
    "can i asking you about anything": "Sure Sir, am here to help you",
    "can you help me": "We will see if i can help you",

    "who made you": "his name is ' abdelrhman ashraf ' and he is programmer",
    "who made": "his name is ' abdelrhman ashraf ' and he is programmer",
    "what his age": "20 ago, or more than i don't know",
    "what is his age": "20 ago, or more than i don't know",
    "what's his age": "20 ago, or more than i don't know",
    "what is his work": "a programmer",
    "what's his work": "a programmer",
    "what is his job": "a programmer",
    "what's his job": "a programmer",

    "what your best book": "😂 am not reading, am just robot for help you",
    "what your best game": "😂 am not playing, am just robot for help you",
    "what your best food": "😂 am not eating, am just robot for help you",
    "what your best film": "😂 am not watching, am just robot for help you",
    "what your best color": "😂 just the color of page",

    "what is your best book": "😂 am not reading, am just robot for help you",
    "what is your best game": "😂 am not playing, am just robot for help you",
    "what is your best food": "😂 am not eating, am just robot for help you",
    "what is your best film": "😂 am not watching, am just robot for help you",
    "what is your best color": "😂 just the color of page",

    "what's your best book": "😂 am not reading, am just robot for help you",
    "what's your best game": "😂 am not playing, am just robot for help you",
    "what's your best food": "😂 am not eating, am just robot for help you",
    "what's your best film": "😂 am not watching, am just robot for help you",
    "what's your best color": "😂 just the color of page",

    "what is your favourite book": "😂 am not reading, am just robot for help you",
    "what is your favourite game": "😂 am not playing, am just robot for help you",
    "what is your favourite food": "😂 am not eating, am just robot for help you",
    "what is your favourite film": "😂 am not reading, am just robot for help you",
    "what is your favourite color": "😂 just the color of page",

    "what's your favourite book": "😂 am not reading, am just robot for help you",
    "what's your favourite game": "😂 am not playing, am just robot for help you",
    "what's your favourite food": "😂 am not eating, am just robot for help you",
    "what's your favourite film": "😂 am not reading, am just robot for help you",
    "what's your favourite color": "😂 just the color of page",

    "what is your favourite book": "😂 am not reading, am just robot for help you",
    "what is your favourite game": "😂 am not playing, am just robot for help you",
    "what is your favourite food": "😂 am not eating, am just robot for help you",
    "what is your favourite film": "😂 am not reading, am just robot for help you",
    "what is your favourite color": "😂 just the color of page",


    "what best describes you": "about nothing!!, nothing is nothing 😂",

    "best of luck": "and you my friend",
    "good luck": "and you my friend",
    "good luck my friend": "and you my friend",
    "good luck friend": "and you my friend",
    "good luck my friend": "and you my friend",

    "see you again": "and you my friend",

    "can i see you": "yes already see me now, or what 😃",

    "goodbye": "i hope to see you again 💖",
    "i am leaving": "Sad to see you go",
    "i'am leaving": "Sad to see you go",
    "i am go now": "i hope to see you again 💖",
    "i'am go now": "i hope to see you again 💖",
    "i am go": "i hope to see you again 💖",
    "i'am go": "i hope to see you again 💖",
    "have a good day": "goodbye!",
    "bye": "goodbye!",
    "see you later": "i hope to see you again 💖",
    "cya": "goodbye!",
    "gotta go": "Sad to see you go!",
    "i have to go": "Sad to see you go!",

    "how old": "am a robot, no age",
    "how old are you": "am a robot, no age",
    "what is your age": "am a robot, no age",
    "what's your age": "am a robot, no age",

    "what should i call you": "my name is ' globot ' ",
    "who are you": "my name is ' globot ' ",

    hey: "hi",
    "what's up": "welcome Sir",
    "hi": "Hi Sir",

    "one": "1",
    "two": "2",
    "three": "3",
    "four": "4",
    "five": "5",
    "six": "6",
    "seven": "7",
    "eight": "8",
    "nine": "9",
    "ten": "10",

    "i want google": `<div class="gcse-search"></div>`,

    "go": "Let's go 🎢😂",
    "let's go": "Let's go 🎢😂",
    "let is go": "Let's go 🎢😂",
    "come on": "Let's go 🎢😂",
    "together": "Let's go 🎢😂",
    "yes": "ya yes, Let's go 🎢😂",
    "go ahead": "ya yes, Let's go 🎢😂",

    "go away": "Why Sir am don't understand 😥",
    "go away from me": "Why Sir am don't understand 😥",
    "are you kidding me": "Why Sir am don't understand 😥",
    "are you buling me": "Why Sir am don't understand 😥",
    "are you insane": "Why Sir am don't understand 😥",
    "get stop now": "Why Sir am don't understand 😥",
    "get stop": "Why Sir am don't understand 😥",
    "stop now": "Why Sir am don't understand 😥",
    "stop": "Why Sir am don't understand 😥",
    "are you hate me": "Why Sir am don't understand 😥",
    "are you hating me": "Why Sir am don't understand 😥",

    "are you robot": "Yes Sir, and am here to help you",
    "are you life": "No Sir, am just robot made from a programmer",
    "are you live": "No Sir, am just robot made from a programmer",
    "are you live": "No Sir, am just robot made from a programmer",

    "so hot": "what happend Sir!!?",
    "hot": "what happend Sir!!?",
    "am die globot": "what happend Sir!!?",
    "i'am die globot": "what happend Sir!!?",


}